// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd
// https://www.progressiverobot.com
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// The self-service portal as it is served: the page, the script it loads, and
// the headers both carry. Three string literals and nothing else - the routes
// that serve them are RestApiServer's HandlePortalPage_ and
// HandlePortalScript_, which declare these three names.
//
// Literals rather than files, deliberately: the portal answers on a listener
// that may be the only thing an installation has, and a page that depends on a
// file beside the binary is a page that is missing where somebody most needs
// it. build/check-portal-script.py parses the script from this file, so the
// three definitions keep their shape: a name, "=", and the string that follows.

#include "StdAfx.h"

namespace HM
{

   // The self-service page. Static: nothing in it comes from the server's
   // data, so nothing is escaped into it - every value the user sees is
   // fetched by the script as JSON and written into the page as text. The
   // markup and the script are two responses so the page can carry a
   // Content-Security-Policy that allows no inline script at all.
   const char *PortalHtml =
      "<!doctype html>\n"
      "<html lang=\"en\">\n"
      "<head>\n"
      "<meta charset=\"utf-8\">\n"
      "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
      "<title>hMailServer - my account</title>\n"
      "<style>\n"
      "body{font-family:system-ui,'Segoe UI',sans-serif;margin:0;background:#f4f5f7;color:#1c1e21}\n"
      "main{max-width:36rem;margin:2rem auto;padding:0 1rem}\n"
      "section{background:#fff;border:1px solid #d9dce1;border-radius:.5rem;padding:1rem 1.25rem;margin-bottom:1rem}\n"
      "h1{font-size:1.4rem;margin:0 0 1rem}h2{font-size:1.05rem;margin:0 0 .75rem}\n"
      "label{display:block;margin:.5rem 0 .25rem;font-size:.9rem}\n"
      "input[type=text],input[type=password],input[type=date],textarea{width:100%;box-sizing:border-box;padding:.45rem;border:1px solid #b9bec7;border-radius:.3rem;font:inherit}\n"
      "textarea{min-height:6rem}\n"
      "button{margin-top:.75rem;padding:.45rem .9rem;border:0;border-radius:.3rem;background:#2f81f7;color:#fff;font:inherit;cursor:pointer}\n"
      "button.secondary{background:#e4e6ea;color:#1c1e21}\n"
      ".status{margin-top:.5rem;font-size:.9rem;min-height:1.2rem}.status.error{color:#b42318}.status.ok{color:#067647}\n"
      ".meter{height:.5rem;background:#e4e6ea;border-radius:.25rem;overflow:hidden;margin:.4rem 0}.meter div{height:100%;background:#2f81f7}\n"
      ".held{border-top:1px solid #e4e6ea;padding:.6rem 0}.held-subject{font-weight:600}.held-detail{font-size:.85rem;color:#4b5563;margin:.2rem 0 .4rem}.held button{margin:0 .5rem 0 0}\n"
      "select{width:100%;box-sizing:border-box;padding:.45rem;border:1px solid #b9bec7;border-radius:.3rem;font:inherit;background:#fff}\n"
      ".msg{border-top:1px solid #e4e6ea;padding:.5rem 0;cursor:pointer}.msg.unseen .msg-subject{font-weight:600}.msg-detail{font-size:.85rem;color:#4b5563}.msg-reply{margin-left:1.25rem;border-left:2px solid #e4e6ea;padding-left:.5rem}\n"
      ".msg{display:flex;gap:.5rem;align-items:flex-start}.msg-body{flex:1;min-width:0}.msg-cursor{background:#eef4ff;outline:2px solid #2f81f7;outline-offset:-2px}\n"
      "#bulk-bar{margin:.5rem 0}#bulk-bar button{margin:0 .5rem .5rem 0}#bulk-bar select{width:auto;display:inline-block;margin-right:.5rem}\n"
      "pre{white-space:pre-wrap;word-break:break-word;font:inherit;background:#f4f5f7;padding:.75rem;border-radius:.3rem;max-height:30rem;overflow:auto}\n"
      "iframe{width:100%;min-height:24rem;border:1px solid #d9dce1;border-radius:.3rem;background:#fff}\n"
      "#message-actions{margin:.5rem 0}#message-actions button{margin:0 .5rem .5rem 0}#message-actions select{width:auto;display:inline-block;margin-right:.5rem}\n"
      "input[type=search]{width:100%;box-sizing:border-box;padding:.45rem;border:1px solid #b9bec7;border-radius:.3rem;font:inherit}.search button{margin:.5rem .5rem 0 0}.search label.inline{display:inline-block;margin:.5rem 0 0}\n"
      "[hidden]{display:none!important}\n"
      "</style>\n"
      "</head>\n"
      "<body>\n"
      "<main>\n"
      "<h1>My account</h1>\n"
      "<section id=\"signin\">\n"
      "<h2>Sign in</h2>\n"
      "<form id=\"signin-form\">\n"
      "<label for=\"address\">E-mail address</label><input id=\"address\" type=\"text\" autocomplete=\"username\" required>\n"
      "<label for=\"password\">Password</label><input id=\"password\" type=\"password\" autocomplete=\"current-password\" required>\n"
      "<button type=\"submit\">Sign in</button>\n"
      "<div id=\"signin-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "<div id=\"account\" hidden>\n"
      "<section>\n"
      "<h2 id=\"who\"></h2>\n"
      "<div id=\"quota\"></div>\n"
      "<div class=\"meter\"><div id=\"quota-bar\" style=\"width:0\"></div></div>\n"
      "<div id=\"password-changed\"></div>\n"
      "<button id=\"signout\" class=\"secondary\" type=\"button\">Sign out</button>\n"
      "</section>\n"
      "<section>\n"
      "<h2>Out of office</h2>\n"
      "<form id=\"vacation-form\">\n"
      "<label><input id=\"vacation-enabled\" type=\"checkbox\"> Send an automatic reply</label>\n"
      "<label for=\"vacation-subject\">Subject</label><input id=\"vacation-subject\" type=\"text\" maxlength=\"200\">\n"
      "<label for=\"vacation-message\">Message</label><textarea id=\"vacation-message\" maxlength=\"20000\"></textarea>\n"
      "<label><input id=\"vacation-expires\" type=\"checkbox\"> Stop replying after</label>\n"
      "<input id=\"vacation-expires-date\" type=\"date\">\n"
      "<button type=\"submit\">Save</button>\n"
      "<div id=\"vacation-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "<section id=\"quarantine-section\">\n"
      "<h2>Held as suspected spam</h2>\n"
      "<p id=\"quarantine-note\"></p>\n"
      "<div id=\"quarantine-list\"></div>\n"
      "<div id=\"quarantine-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</section>\n"
      "<section id=\"mail-section\">\n"
      "<h2>Mail</h2>\n"
      "<label for=\"folder\">Folder</label><select id=\"folder\"></select>\n"
      "<form id=\"mail-search-form\" class=\"search\"><label for=\"mail-search\">Search</label><input id=\"mail-search\" type=\"search\" maxlength=\"200\"><label class=\"inline\"><input id=\"mail-search-everywhere\" type=\"checkbox\"> All folders</label><button type=\"submit\" class=\"secondary\">Search</button><button id=\"mail-search-clear\" type=\"button\" class=\"secondary\">Clear</button></form>\n"
      "<div id=\"bulk-bar\" hidden><span id=\"bulk-count\"></span> <button id=\"bulk-read\" class=\"secondary\" type=\"button\">Mark read</button><button id=\"bulk-unread\" class=\"secondary\" type=\"button\">Mark unread</button><button id=\"bulk-delete\" class=\"secondary\" type=\"button\">Delete</button><select id=\"bulk-move\" aria-label=\"Move selected to\"></select><button id=\"bulk-move-go\" class=\"secondary\" type=\"button\">Move</button><button id=\"bulk-clear\" class=\"secondary\" type=\"button\">Clear</button></div>\n"
      "<p class=\"held-detail\">Arrow keys or j and k move, Enter opens, x ticks the box.</p>\n"
      "<div id=\"message-list\"></div>\n"
      "<div id=\"message-view\" hidden>\n"
      "<button id=\"message-back\" class=\"secondary\" type=\"button\">Back to the list</button>\n"
      "<div id=\"message-subject\" class=\"held-subject\"></div>\n"
      "<div id=\"message-meta\" class=\"held-detail\"></div>\n"
      "<div id=\"message-actions\"><button id=\"message-edit\" class=\"secondary\" type=\"button\" hidden>Edit draft</button><button id=\"message-reply\" class=\"secondary\" type=\"button\">Reply</button><button id=\"message-reply-all\" class=\"secondary\" type=\"button\">Reply all</button><button id=\"message-forward\" class=\"secondary\" type=\"button\">Forward</button><button id=\"message-html-toggle\" class=\"secondary\" type=\"button\" hidden>Show as sent</button><button id=\"message-unread\" class=\"secondary\" type=\"button\">Mark as unread</button><button id=\"message-flag\" class=\"secondary\" type=\"button\">Flag</button><button id=\"message-delete\" class=\"secondary\" type=\"button\">Delete</button><select id=\"message-move\" aria-label=\"Move to\"></select><button id=\"message-move-go\" class=\"secondary\" type=\"button\">Move</button></div>\n"
      "<pre id=\"message-text\"></pre>\n"
      "<iframe id=\"message-html\" sandbox=\"allow-popups allow-popups-to-escape-sandbox\" referrerpolicy=\"no-referrer\" title=\"The message as it was sent\" hidden></iframe>\n"
      "<div id=\"message-attachments\" class=\"held-detail\"></div>\n"
      "</div>\n"
      "<div id=\"mail-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</section>\n"
      "<section id=\"compose-section\">\n"
      "<h2>New message</h2>\n"
      "<form id=\"compose-form\">\n"
      "<label for=\"compose-to\">To</label><input id=\"compose-to\" type=\"text\" required>\n"
      "<label for=\"compose-cc\">Cc</label><input id=\"compose-cc\" type=\"text\">\n"
      "<label for=\"compose-bcc\">Bcc</label><input id=\"compose-bcc\" type=\"text\">\n"
      "<label for=\"compose-subject\">Subject</label><input id=\"compose-subject\" type=\"text\" maxlength=\"500\">\n"
      "<label for=\"compose-text\">Message</label><textarea id=\"compose-text\"></textarea>\n"
      "<label for=\"compose-files\">Files</label><input id=\"compose-files\" type=\"file\" multiple><div id=\"compose-files-note\" class=\"held-detail\"></div>\n"
      "<button type=\"submit\">Send</button><button id=\"compose-save\" type=\"button\" class=\"secondary\">Save draft</button>\n"
      "<div id=\"compose-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "<section id=\"settings-section\">\n"
      "<h2>Settings</h2>\n"
      "<form id=\"settings-form\">\n"
      "<label for=\"name-first\">First name</label><input id=\"name-first\" type=\"text\" maxlength=\"100\">\n"
      "<label for=\"name-last\">Last name</label><input id=\"name-last\" type=\"text\" maxlength=\"100\">\n"
      "<label><input id=\"forward-enabled\" type=\"checkbox\"> Forward my mail</label>\n"
      "<label for=\"forward-address\">Forward to</label><input id=\"forward-address\" type=\"text\" autocomplete=\"off\">\n"
      "<label><input id=\"forward-keep\" type=\"checkbox\"> Keep a copy here</label>\n"
      "<label><input id=\"signature-enabled\" type=\"checkbox\"> Add a signature to what I send</label>\n"
      "<label for=\"signature-text\">Signature</label><textarea id=\"signature-text\" maxlength=\"20000\"></textarea>\n"
      "<button type=\"submit\">Save</button>\n"
      "<div id=\"settings-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "<section id=\"filter-section\">\n"
      "<h2>Filters</h2>\n"
      "<p class=\"held-detail\">A Sieve script, run on every message as it arrives. It is checked before it is saved.</p>\n"
      "<form id=\"filter-form\">\n"
      "<label for=\"filter-script\">Script</label><textarea id=\"filter-script\" spellcheck=\"false\"></textarea>\n"
      "<button type=\"submit\">Save</button>\n"
      "<div id=\"filter-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "<section id=\"password-section\">\n"
      "<h2>Change password</h2>\n"
      "<form id=\"password-form\">\n"
      "<label for=\"current\">Current password</label><input id=\"current\" type=\"password\" autocomplete=\"current-password\" required>\n"
      "<label for=\"new\">New password</label><input id=\"new\" type=\"password\" autocomplete=\"new-password\" required>\n"
      "<label for=\"confirm\">New password again</label><input id=\"confirm\" type=\"password\" autocomplete=\"new-password\" required>\n"
      "<div id=\"otp-row\" hidden><label for=\"otp\">Code from your authenticator app</label><input id=\"otp\" type=\"text\" inputmode=\"numeric\" autocomplete=\"one-time-code\"></div>\n"
      "<button type=\"submit\">Change password</button>\n"
      "<div id=\"password-status\" class=\"status\" aria-live=\"polite\"></div>\n"
      "</form>\n"
      "</section>\n"
      "</div>\n"
      "</main>\n"
      "<script src=\"/portal.js\"></script>\n"
      "</body>\n"
      "</html>\n";

   const char *PortalScript =
      "(function () {\n"
      "  'use strict';\n"
      "  var el = function (id) { return document.getElementById(id); };\n"
      "  var say = function (id, text, ok) { var s = el(id); s.textContent = text || ''; s.className = 'status' + (text ? (ok ? ' ok' : ' error') : ''); };\n"
      "  // The password is sent exactly once, to start the session; from then on\n"
      "  // the browser's cookie is the credential and nothing is kept in memory.\n"
      "  var call = function (method, path, body, extra) {\n"
      "    var h = {};\n"
      "    if (extra) { for (var k in extra) { if (extra[k]) { h[k] = extra[k]; } } }\n"
      "    if (method !== 'GET') { h['X-Requested-With'] = 'hMailServer'; }\n"
      "    var options = { method: method, headers: h, cache: 'no-store', credentials: 'same-origin' };\n"
      "    if (body !== undefined) { h['Content-Type'] = 'application/json'; options.body = JSON.stringify(body); }\n"
      "    return fetch(path, options).then(function (response) {\n"
      "      return response.text().then(function (text) {\n"
      "        var data = null;\n"
      "        try { data = text ? JSON.parse(text) : null; } catch (e) { data = null; }\n"
      "        if (response.status === 401 && path !== '/api/v1/me' && path !== '/api/v1/session' && !el('account').hidden) {\n"
      "          showSignIn();\n"
      "          say('signin-status', 'Your session has ended. Sign in again.', false);\n"
      "        }\n"
      "        return { status: response.status, data: data, otp: response.headers.get('X-hMailServer-OTP') };\n"
      "      });\n"
      "    });\n"
      "  };\n"
      "  var describe = function (result, fallback) {\n"
      "    if (result.data && result.data.error) { return result.data.error; }\n"
      "    if (result.status === 401) { return 'The address or password is not right, or the session has ended.'; }\n"
      "    if (result.status === 429) { return 'Too many attempts; wait a minute and try again.'; }\n"
      "    return fallback + ' (' + result.status + ')';\n"
      "  };\n"
      "  var format = function (bytes) {\n"
      "    if (bytes >= 1073741824) { return (bytes / 1073741824).toFixed(1) + ' GB'; }\n"
      "    if (bytes >= 1048576) { return (bytes / 1048576).toFixed(1) + ' MB'; }\n"
      "    if (bytes >= 1024) { return (bytes / 1024).toFixed(0) + ' KB'; }\n"
      "    return bytes + ' bytes';\n"
      "  };\n"
      "  var showSignIn = function () {\n"
      "    el('account').hidden = true;\n"
      "    el('signin').hidden = false;\n"
      "    el('address').focus();\n"
      "  };\n"
      "  // Every value from the server is written as text, never as markup.\n"
      "  var node = function (tag, text, className) {\n"
      "    var n = document.createElement(tag);\n"
      "    if (text !== undefined) { n.textContent = text; }\n"
      "    if (className) { n.className = className; }\n"
      "    return n;\n"
      "  };\n"
      "  var renderQuarantine = function (held) {\n"
      "    var list = el('quarantine-list');\n"
      "    while (list.firstChild) { list.removeChild(list.firstChild); }\n"
      "    if (!held.enabled) { el('quarantine-note').textContent = 'The server does not hold suspected spam for review; it refuses it.'; return; }\n"
      "    if (!held.messages.length) { el('quarantine-note').textContent = 'Nothing is being held for you.'; return; }\n"
      "    el('quarantine-note').textContent = held.messages.length + ' message' + (held.messages.length === 1 ? '' : 's') + ' held as suspected spam. Releasing one delivers it to you; deleting one is final.';\n"
      "    held.messages.forEach(function (m) {\n"
      "      var row = node('div', undefined, 'held');\n"
      "      row.appendChild(node('div', m.subject || '(no subject)', 'held-subject'));\n"
      "      row.appendChild(node('div', 'From ' + m.sender + ' - ' + m.created + ' - ' + m.reason + ' (score ' + m.score + ')', 'held-detail'));\n"
      "      var release = node('button', 'Release to my inbox'); release.type = 'button';\n"
      "      var discard = node('button', 'Delete', 'secondary'); discard.type = 'button';\n"
      "      release.addEventListener('click', function () {\n"
      "        call('POST', '/api/v1/me/quarantine/' + m.id + '/release').then(function (result) {\n"
      "          say('quarantine-status', result.status === 200 ? 'Released. It will arrive in your inbox shortly.' : describe(result, 'Could not release'), result.status === 200);\n"
      "          loadQuarantine();\n"
      "        });\n"
      "      });\n"
      "      discard.addEventListener('click', function () {\n"
      "        call('DELETE', '/api/v1/me/quarantine/' + m.id).then(function (result) {\n"
      "          say('quarantine-status', result.status === 200 ? 'Deleted.' : describe(result, 'Could not delete'), result.status === 200);\n"
      "          loadQuarantine();\n"
      "        });\n"
      "      });\n"
      "      row.appendChild(release); row.appendChild(discard);\n"
      "      list.appendChild(row);\n"
      "    });\n"
      "  };\n"
      "  var loadQuarantine = function () {\n"
      "    return call('GET', '/api/v1/me/quarantine').then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderQuarantine(result.data); }\n"
      "    });\n"
      "  };\n"
      "  // The mailbox, read-only: the folder tree, the newest messages of\n"
      "  // the chosen folder, and one message's text. Nothing here writes.\n"
      "  var flatten = function (list, into) {\n"
      "    list.forEach(function (f) { into.push(f); flatten(f.subfolders || [], into); });\n"
      "    return into;\n"
      "  };\n"
      "  var renderMessage = function (m) {\n"
      "    el('message-list').hidden = true;\n"
      "    el('message-view').hidden = false;\n"
      "    el('message-subject').textContent = m.subject || '(no subject)';\n"
      "    el('message-meta').textContent = 'From ' + (m.from || '?') + (m.to ? ' to ' + m.to : '') + (m.cc ? ', cc ' + m.cc : '') + ' - ' + (m.date || m.received);\n"
      "    var text = m.text || '';\n"
      "    if (!text && m.html) {\n"
      "      // An HTML-only message is read as a document and only its text is\n"
      "      // shown: nothing in it runs, loads or renders.\n"
      "      text = new DOMParser().parseFromString(m.html, 'text/html').body.textContent || '';\n"
      "    }\n"
      "    if (m.truncated) { text = 'This message is too large to show here; open it in your mail program.' + ((m.attachments || []).length ? ' Its attachments can be downloaded below.' : ''); }\n"
      "    el('message-text').textContent = text || '(no text)';\n"
      "    var attachments = el('message-attachments');\n"
      "    while (attachments.firstChild) { attachments.removeChild(attachments.firstChild); }\n"
      "    if ((m.attachments || []).length) {\n"
      "      attachments.appendChild(node('span', 'Attachments: '));\n"
      "      m.attachments.forEach(function (a, i) {\n"
      "        var link = node('a', a.name + ' (' + format(a.size) + ')');\n"
      "        link.href = '/api/v1/me/messages/' + m.id + '/attachments/' + a.index;\n"
      "        link.setAttribute('download', a.name);\n"
      "        if (i > 0) { attachments.appendChild(node('span', ', ')); }\n"
      "        attachments.appendChild(link);\n"
      "      });\n"
      "    }\n"
      "    current = m;\n"
      "    renderActions();\n"
      "    el('message-html-toggle').hidden = !m.html || m.truncated;\n"
      "    renderHtml();\n"
      "  };\n"
      "  var openMessage = function (id) {\n"
      "    say('mail-status', '', true);\n"
      "    call('GET', '/api/v1/me/messages/' + id).then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderMessage(result.data); if (!result.data.flags.seen) { setFlags({ seen: true }, true); } return; }\n"
      "      say('mail-status', describe(result, 'Could not open the message'), false);\n"
      "    });\n"
      "  };\n"
      "  var renderMessages = function (page) {\n"
      "    var list = el('message-list');\n"
      "    while (list.firstChild) { list.removeChild(list.firstChild); }\n"
      "    listRows = []; cursor = -1;\n"
      "    if (!page.messages.length) { selected = {}; renderBulk(); list.appendChild(node('div', page.query ? 'Nothing matched.' : 'This folder is empty.', 'msg-detail')); renderSearchNote(list, page); return; }\n"
      "    var shown = {};\n"
      "    page.messages.forEach(function (m) {\n"
      "      shown[m.id] = true;\n"
      "      // A reply is indented under what it answers. The list is newest\n"
      "      // first, so 'the root was seen already' would indent the original.\n"
      "      var inThread = !!(m.in_reply_to || (m.references || '').trim());\n"
      "      var row = node('div', undefined, (m.flags.seen ? 'msg' : 'msg unseen') + (inThread ? ' msg-reply' : ''));\n"
      "      var box = document.createElement('input'); box.type = 'checkbox'; box.checked = !!selected[m.id]; box.setAttribute('aria-label', 'Select');\n"
      "      box.addEventListener('click', function (event) { event.stopPropagation(); selected[m.id] = box.checked; renderBulk(); });\n"
      "      var body = node('div', undefined, 'msg-body');\n"
      "      body.appendChild(node('div', m.subject || '(no subject)', 'msg-subject'));\n"
      "      body.appendChild(node('div', (m.from || '?') + ' - ' + (m.date || m.received) + ' - ' + format(m.size) + (m.folder ? ' - in ' + m.folder : ''), 'msg-detail'));\n"
      "      row.appendChild(box); row.appendChild(body);\n"
      "      body.addEventListener('click', function () { openMessage(m.id); });\n"
      "      listRows.push({ id: m.id, row: row, box: box });\n"
      "      list.appendChild(row);\n"
      "    });\n"
      "    Object.keys(selected).forEach(function (k) { if (!shown[k]) { delete selected[k]; } });\n"
      "    setCursor(0);\n"
      "    renderBulk();\n"
      "    if (!page.query && page.total > page.messages.length && page.messages.length) {\n"
      "      var last = page.messages[page.messages.length - 1];\n"
      "      var older = node('button', 'Older messages', 'secondary'); older.type = 'button';\n"
      "      older.addEventListener('click', function () { search.before = last.uid; loadMessages(); });\n"
      "      var note = node('div', (search.before ? 'Older than message ' + search.before + ': ' : 'The newest ') + page.messages.length + ' of ' + page.total + ' are shown. ', 'msg-detail');\n"
      "      note.appendChild(older);\n"
      "      list.appendChild(note);\n"
      "    }\n"
      "    renderSearchNote(list, page);\n"
      "  };\n"
      "  var loadMessages = function () {\n"
      "    var id = el('folder').value;\n"
      "    var url;\n"
      "    if (search.text && search.everywhere) {\n"
      "      url = '/api/v1/me/search?q=' + encodeURIComponent(search.text) + '&limit=200';\n"
      "    } else {\n"
      "      if (!id) { renderMessages({ total: 0, messages: [] }); return; }\n"
      "      url = '/api/v1/me/folders/' + id + '/messages';\n"
      "      if (search.text) { url += '?q=' + encodeURIComponent(search.text) + (search.before ? '&before_uid=' + search.before : ''); }\n"
      "      else if (search.before) { url += '?before_uid=' + search.before; }\n"
      "    }\n"
      "    call('GET', url).then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderMessages(result.data); return; }\n"
      "      say('mail-status', describe(result, 'Could not read the folder'), false);\n"
      "    });\n"
      "  };\n"
      "  var renderFolders = function (tree) {\n"
      "    var select = el('folder');\n"
      "    var chosen = select.value;\n"
      "    while (select.firstChild) { select.removeChild(select.firstChild); }\n"
      "    var folders = flatten(tree.folders, []);\n"
      "    (tree.shared || []).forEach(function (share) { flatten(share.folders, folders); });\n"
      "    allFolders = folders;\n"
      "    folders.forEach(function (f) {\n"
      "      var option = node('option', f.path + (f.unseen ? ' (' + f.unseen + ')' : ''));\n"
      "      option.value = f.id;\n"
      "      select.appendChild(option);\n"
      "    });\n"
      "    var inbox = folders.filter(function (f) { return f.path.toUpperCase() === 'INBOX'; })[0];\n"
      "    select.value = chosen || (inbox ? inbox.id : (folders.length ? folders[0].id : ''));\n"
      "    loadMessages();\n"
      "  };\n"
      "  var loadFolders = function () {\n"
      "    return call('GET', '/api/v1/me/folders').then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderFolders(result.data); }\n"
      "    });\n"
      "  };\n"
      "  el('folder').addEventListener('change', function () { selected = {}; cursor = -1; search.before = 0; showList(); loadMessages(); });\n"
      "  el('message-back').addEventListener('click', function () { el('message-view').hidden = true; el('message-list').hidden = false; });\n"
      "  // Acting on the open message: read or unread, flag, move, delete.\n"
      "  // Each is one call, and the folder counts are re-read afterwards.\n"
      "  var current = null;\n"
      "  var allFolders = [];\n"
      "  var replyTo = null;\n"
      "  var showList = function () { el('message-view').hidden = true; el('message-list').hidden = false; };\n"
      "  var renderActions = function () {\n"
      "    if (!current) { return; }\n"
      "    el('message-unread').textContent = current.flags.seen ? 'Mark as unread' : 'Mark as read';\n"
      "    el('message-flag').textContent = current.flags.flagged ? 'Remove flag' : 'Flag';\n"
      "    el('message-edit').hidden = !current.flags.draft;\n"
      "    var select = el('message-move');\n"
      "    while (select.firstChild) { select.removeChild(select.firstChild); }\n"
      "    var home = allFolders.filter(function (f) { return f.id === current.folder_id; })[0];\n"
      "    allFolders.forEach(function (f) {\n"
      "      if (f.id === current.folder_id || !f.writable || (home && f.account_id !== home.account_id)) { return; }\n"
      "      var option = node('option', f.path); option.value = f.id; select.appendChild(option);\n"
      "    });\n"
      "  };\n"
      "  var setFlags = function (flags, quiet) {\n"
      "    if (!current) { return; }\n"
      "    var id = current.id;\n"
      "    return call('PUT', '/api/v1/me/messages/' + id + '/flags', flags).then(function (result) {\n"
      "      if (result.status === 200 && result.data) {\n"
      "        if (current && current.id === id) { current.flags = result.data.flags; renderActions(); }\n"
      "        loadFolders();\n"
      "        return;\n"
      "      }\n"
      "      if (!quiet) { say('mail-status', describe(result, 'Could not change the flags'), false); }\n"
      "    });\n"
      "  };\n"
      "  el('message-unread').addEventListener('click', function () { if (current) { setFlags({ seen: !current.flags.seen }, false); } });\n"
      "  el('message-flag').addEventListener('click', function () { if (current) { setFlags({ flagged: !current.flags.flagged }, false); } });\n"
      "  el('message-delete').addEventListener('click', function () {\n"
      "    if (!current) { return; }\n"
      "    call('DELETE', '/api/v1/me/messages/' + current.id).then(function (result) {\n"
      "      if (result.status === 200) { say('mail-status', result.data && result.data.deleted ? 'Deleted.' : 'Moved to the trash folder.', true); current = null; showList(); loadFolders(); return; }\n"
      "      say('mail-status', describe(result, 'Could not delete'), false);\n"
      "    });\n"
      "  });\n"
      "  el('message-move-go').addEventListener('click', function () {\n"
      "    var target = el('message-move').value;\n"
      "    if (!current || !target) { return; }\n"
      "    call('POST', '/api/v1/me/messages/' + current.id + '/move', { folder_id: Number(target) }).then(function (result) {\n"
      "      if (result.status === 200) { say('mail-status', 'Moved.', true); current = null; showList(); loadFolders(); return; }\n"
      "      say('mail-status', describe(result, 'Could not move'), false);\n"
      "    });\n"
      "  });\n"
      "  var render = function (me) {\n"
      "    el('who').textContent = me.address;\n"
      "    var used = me.quota.used_bytes, limit = me.quota.limit_mb * 1048576;\n"
      "    if (limit > 0) {\n"
      "      el('quota').textContent = format(used) + ' of ' + me.quota.limit_mb + ' MB used';\n"
      "      el('quota-bar').style.width = Math.min(100, Math.round(100 * used / limit)) + '%';\n"
      "    } else {\n"
      "      el('quota').textContent = format(used) + ' used, no limit';\n"
      "      el('quota-bar').style.width = '0';\n"
      "    }\n"
      "    el('password-changed').textContent = me.password_changed ? 'Password last changed ' + me.password_changed : '';\n"
      "    el('vacation-enabled').checked = !!me.vacation.enabled;\n"
      "    el('vacation-subject').value = me.vacation.subject || '';\n"
      "    el('vacation-message').value = me.vacation.message || '';\n"
      "    el('vacation-expires').checked = !!me.vacation.expires;\n"
      "    el('vacation-expires-date').value = me.vacation.expires_date || '';\n"
      "    el('otp-row').hidden = !me.second_factor;\n"
      "    el('password-section').hidden = !!me.directory_linked;\n"
      "    el('signin').hidden = true;\n"
      "    el('account').hidden = false;\n"
      "  };\n"
      "  var load = function (quiet) {\n"
      "    return call('GET', '/api/v1/me').then(function (result) {\n"
      "      if (result.status === 200 && result.data) { me = String(result.data.address || '').toLowerCase(); render(result.data); loadQuarantine(); loadFolders(); loadSettings(); return true; }\n"
      "      if (!quiet) { say('signin-status', describe(result, 'Could not sign in'), false); }\n"
      "      showSignIn();\n"
      "      return false;\n"
      "    });\n"
      "  };\n"
      "  el('signin-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    say('signin-status', '', true);\n"
      "    var address = el('address').value.trim(), password = el('password').value;\n"
      "    el('password').value = '';\n"
      "    var basic = 'Basic ' + btoa(unescape(encodeURIComponent(address + ':' + password)));\n"
      "    call('POST', '/api/v1/session', undefined, { 'Authorization': basic }).then(function (result) {\n"
      "      if (result.status === 201) { load(false); return; }\n"
      "      say('signin-status', describe(result, 'Could not sign in'), false);\n"
      "    });\n"
      "  });\n"
      "  el('signout').addEventListener('click', function () {\n"
      "    call('DELETE', '/api/v1/session').then(function () { showSignIn(); });\n"
      "  });\n"
      "  el('vacation-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    var body = {\n"
      "      enabled: el('vacation-enabled').checked,\n"
      "      subject: el('vacation-subject').value,\n"
      "      message: el('vacation-message').value,\n"
      "      expires: el('vacation-expires').checked,\n"
      "      expires_date: el('vacation-expires-date').value\n"
      "    };\n"
      "    call('PUT', '/api/v1/me/vacation', body).then(function (result) {\n"
      "      say('vacation-status', result.status === 200 ? 'Saved.' : describe(result, 'Could not save'), result.status === 200);\n"
      "    });\n"
      "  });\n"
      "  el('password-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    var current = el('current').value, fresh = el('new').value, confirm = el('confirm').value;\n"
      "    if (fresh !== confirm) { say('password-status', 'The two new passwords differ.', false); return; }\n"
      "    call('POST', '/api/v1/me/password', { current: current, 'new': fresh }, { 'X-hMailServer-OTP': el('otp').value.trim() }).then(function (result) {\n"
      "      if (result.status === 200) {\n"
      "        el('current').value = ''; el('new').value = ''; el('confirm').value = ''; el('otp').value = '';\n"
      "        say('password-status', 'Password changed. Other browsers signed in to this account have been signed out.', true);\n"
      "        load(true);\n"
      "        return;\n"
      "      }\n"
      "      if (result.otp === 'required') { el('otp-row').hidden = false; say('password-status', 'Enter the code from your authenticator app.', false); return; }\n"
      "      say('password-status', describe(result, 'Could not change the password'), false);\n"
      "    });\n"
      "  });\n"
      "  el('compose-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    say('compose-status', '', true);\n"
      "    var body = composeBody();\n"
      "    readFiles().then(function (files) {\n"
      "    files = carried.concat(files);\n"
      "    if (files.length) { body.attachments = files; }\n"
      "    return call('POST', '/api/v1/me/messages', body); }, function (why) { say('compose-status', why, false); return null; }).then(function (result) {\n"
      "      if (!result) { return; }\n"
      "      if (result.status === 201) {\n"
      "        el('compose-to').value = ''; el('compose-cc').value = ''; el('compose-bcc').value = ''; el('compose-subject').value = ''; el('compose-text').value = '';\n"
      "        carried = [];\n"
      "        el('compose-files').value = ''; el('compose-files-note').textContent = '';\n"
      "        say('compose-status', 'Sent.', true);\n"
      "        replyTo = null;\n"
      "        if (draftId) { var gone = draftId; draftId = 0; call('DELETE', '/api/v1/me/messages/' + gone + '?permanent=1').then(function () { loadFolders(); }); return; }\n"
      "        loadFolders();\n"
      "        return;\n"
      "      }\n"
      "      say('compose-status', describe(result, 'Could not send'), false);\n"
      "    });\n"
      "  });\n"
      "  // Search: the text narrows the open folder's list, or every folder.\n"
      "  var search = { text: '', before: 0, everywhere: false };\n"
      "  var renderSearchNote = function (list, page) {\n"
      "    if (!page.query) { return; }\n"
      "    var note = 'Searched ' + page.scanned + ' message' + (page.scanned === 1 ? '' : 's') + ' for \\'' + page.query + '\\'.';\n"
      "    if (page.more) { note += ' Only the newest are shown.'; }\n"
      "    var row = node('div', note, 'msg-detail');\n"
      "    if (!page.complete && page.next_before_uid) {\n"
      "      var older = node('button', 'Search older messages', 'secondary'); older.type = 'button';\n"
      "      older.addEventListener('click', function () { search.before = page.next_before_uid; loadMessages(); });\n"
      "      row.appendChild(older);\n"
      "    }\n"
      "    list.appendChild(row);\n"
      "  };\n"
      "  el('mail-search-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    search.text = el('mail-search').value.trim();\n"
      "    search.before = 0;\n"
      "    search.everywhere = el('mail-search-everywhere').checked;\n"
      "    showList();\n"
      "    loadMessages();\n"
      "  });\n"
      "  el('mail-search-clear').addEventListener('click', function () {\n"
      "    el('mail-search').value = '';\n"
      "    search.text = ''; search.before = 0; search.everywhere = false;\n"
      "    el('mail-search-everywhere').checked = false;\n"
      "    showList();\n"
      "    loadMessages();\n"
      "  });\n"
      "  // Settings and filters: read on sign-in, written whole on Save.\n"
      "  var renderSettings = function (s) {\n"
      "    el('name-first').value = s.name.first || '';\n"
      "    el('name-last').value = s.name.last || '';\n"
      "    el('forward-enabled').checked = !!s.forwarding.enabled;\n"
      "    el('forward-address').value = s.forwarding.address || '';\n"
      "    el('forward-keep').checked = !!s.forwarding.keep_original;\n"
      "    el('signature-enabled').checked = !!s.signature.enabled;\n"
      "    el('signature-text').value = s.signature.text || '';\n"
      "  };\n"
      "  var loadSettings = function () {\n"
      "    call('GET', '/api/v1/me/settings').then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderSettings(result.data); }\n"
      "    });\n"
      "    call('GET', '/api/v1/me/filters').then(function (result) {\n"
      "      if (result.status === 200 && result.data) { el('filter-script').value = result.data.active || ''; }\n"
      "    });\n"
      "  };\n"
      "  el('settings-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    var body = {\n"
      "      name: { first: el('name-first').value, last: el('name-last').value },\n"
      "      forwarding: { enabled: el('forward-enabled').checked, address: el('forward-address').value, keep_original: el('forward-keep').checked },\n"
      "      signature: { enabled: el('signature-enabled').checked, text: el('signature-text').value, html: '' }\n"
      "    };\n"
      "    call('PUT', '/api/v1/me/settings', body).then(function (result) {\n"
      "      if (result.status === 200 && result.data) { renderSettings(result.data); say('settings-status', 'Saved.', true); return; }\n"
      "      say('settings-status', describe(result, 'Could not save'), false);\n"
      "    });\n"
      "  });\n"
      "  el('filter-form').addEventListener('submit', function (event) {\n"
      "    event.preventDefault();\n"
      "    call('PUT', '/api/v1/me/filters', { script: el('filter-script').value }).then(function (result) {\n"
      "      if (result.status === 200) { say('filter-status', el('filter-script').value.trim() ? 'Saved. The filter runs on every message that arrives from now on.' : 'Removed.', true); return; }\n"
      "      say('filter-status', describe(result, 'Could not save the filter'), false);\n"
      "    });\n"
      "  });\n"
      "  // HTML as it was sent: in a frame with an origin of its own, where\n"
      "  // nothing runs, nothing is fetched from the network and no form is\n"
      "  // submitted. The markup is the server's bytes, never rebuilt here.\n"
      "  var showHtml = false;\n"
      "  var renderHtml = function () {\n"
      "    var frame = el('message-html');\n"
      "    if (!current || !current.html || !showHtml) { frame.hidden = true; frame.removeAttribute('srcdoc'); el('message-text').hidden = false; return; }\n"
      "    var policy = '<meta http-equiv=\"Content-Security-Policy\" content=\"default-src \\'none\\'; style-src \\'unsafe-inline\\'; img-src data:\">';\n"
      "    frame.srcdoc = '<!doctype html><html><head><meta charset=\"utf-8\">' + policy + '<base target=\"_blank\" rel=\"noopener noreferrer\"><style>body{font-family:system-ui,sans-serif;margin:.5rem;word-break:break-word}</style></head><body>' + current.html + '</body></html>';\n"
      "    frame.hidden = false;\n"
      "    el('message-text').hidden = true;\n"
      "  };\n"
      "  el('message-html-toggle').addEventListener('click', function () {\n"
      "    showHtml = !showHtml;\n"
      "    el('message-html-toggle').textContent = showHtml ? 'Show as text' : 'Show as sent';\n"
      "    renderHtml();\n"
      "  });\n"
      "  // Reply and forward prefill the New message form; sending is the\n"
      "  // same call as any other message.\n"
      "  var addressOf = function (header) {\n"
      "    var m = /<([^>]+)>/.exec(header || '');\n"
      "    return m ? m[1] : (header || '').trim();\n"
      "  };\n"
      "  var quoted = function () {\n"
      "    var text = current.text || '';\n"
      "    if (!text && current.html) { text = new DOMParser().parseFromString(current.html, 'text/html').body.textContent || ''; }\n"
      "    return text.split('\\n').map(function (line) { return '> ' + line; }).join('\\n');\n"
      "  };\n"
      "  var prefill = function (to, subject, text) {\n"
      "    el('compose-to').value = to;\n"
      "    el('compose-cc').value = '';\n"
      "    el('compose-bcc').value = '';\n"
      "    carried = [];\n"
      "    el('compose-files').value = ''; el('compose-files-note').textContent = '';\n"
      "    el('compose-subject').value = subject;\n"
      "    el('compose-text').value = text;\n"
      "    el('compose-section').scrollIntoView();\n"
      "    el('compose-text').focus();\n"
      "  };\n"
      "  el('message-reply').addEventListener('click', function () {\n"
      "    if (!current) { return; }\n"
      "    var subject = current.subject || '';\n"
      "    if (!/^re:/i.test(subject)) { subject = 'Re: ' + subject; }\n"
      "    replyTo = current.message_id ? { message_id: current.message_id, references: ((current.references || '') + ' ' + current.message_id).trim(), id: current.id } : null;\n"
      "    draftId = 0;\n"
      "    prefill(addressOf(current.from), subject, '\\n\\nOn ' + (current.date || current.received) + ', ' + (current.from || '') + ' wrote:\\n' + quoted());\n"
      "  });\n"
      "  el('message-reply-all').addEventListener('click', function () {\n"
      "    if (!current) { return; }\n"
      "    var subject = current.subject || '';\n"
      "    if (!/^re:/i.test(subject)) { subject = 'Re: ' + subject; }\n"
      "    replyTo = current.message_id ? { message_id: current.message_id, references: ((current.references || '') + ' ' + current.message_id).trim(), id: current.id } : null;\n"
      "    draftId = 0;\n"
      "    // Everyone on the message but this account, once each, sender first.\n"
      "    var seen = {}; var others = [];\n"
      "    ((current.to || '') + ',' + (current.cc || '')).split(/[,;]/).forEach(function (part) {\n"
      "      var a = addressOf(part); var key = a.toLowerCase();\n"
      "      if (!a || key === me || key === addressOf(current.from).toLowerCase() || seen[key]) { return; }\n"
      "      seen[key] = true; others.push(a);\n"
      "    });\n"
      "    prefill(addressOf(current.from), subject, '\\n\\nOn ' + (current.date || current.received) + ', ' + (current.from || '') + ' wrote:\\n' + quoted());\n"
      "    el('compose-cc').value = others.join(', ');\n"
      "  });\n"
      "  el('message-forward').addEventListener('click', function () {\n"
      "    if (!current) { return; }\n"
      "    var subject = current.subject || '';\n"
      "    if (!/^fwd?:/i.test(subject)) { subject = 'Fwd: ' + subject; }\n"
      "    replyTo = null;\n"
      "    draftId = 0;\n"
      "    prefill('', subject, '\\n\\n---------- Forwarded message ----------\\nFrom: ' + (current.from || '') + '\\nDate: ' + (current.date || current.received) + '\\nSubject: ' + (current.subject || '') + '\\nTo: ' + (current.to || '') + '\\n\\n' + (current.text || quoted()));\n"
      "    carryAttachments(current);\n"
      "  });\n"
      "  // Drafts: saved into the Drafts folder, edited from it, gone on send.\n"
      "  var draftId = 0;\n"
      "  var me = '';\n"
      "  // Attachments of the message being forwarded or edited, held until send.\n"
      "  var carried = [];\n"
      "  var carryAttachments = function (message) {\n"
      "    carried = [];\n"
      "    var list = message.attachments || [];\n"
      "    if (!list.length) { return Promise.resolve(); }\n"
      "    el('compose-files-note').textContent = 'Fetching ' + list.length + ' attachment(s)...';\n"
      "    return Promise.all(list.map(function (a) {\n"
      "      return fetch('/api/v1/me/messages/' + message.id + '/attachments/' + a.index, { cache: 'no-store', credentials: 'same-origin' }).then(function (response) {\n"
      "        if (response.status !== 200) { throw new Error(a.name); }\n"
      "        return response.blob();\n"
      "      }).then(function (blob) {\n"
      "        return new Promise(function (resolve, reject) {\n"
      "          var reader = new FileReader();\n"
      "          reader.onload = function () { resolve({ name: a.name, type: blob.type || 'application/octet-stream', data: String(reader.result).split(',')[1] || '' }); };\n"
      "          reader.onerror = function () { reject(new Error(a.name)); };\n"
      "          reader.readAsDataURL(blob);\n"
      "        });\n"
      "      });\n"
      "    })).then(function (files) {\n"
      "      carried = files;\n"
      "      el('compose-files-note').textContent = 'Attached from the original: ' + files.map(function (f) { return f.name; }).join(', ');\n"
      "    }, function (why) {\n"
      "      carried = [];\n"
      "      el('compose-files-note').textContent = 'The attachment ' + why.message + ' could not be fetched, so it is not attached.';\n"
      "    });\n"
      "  };\n"
      "  var composeBody = function () {\n"
      "    var body = { to: el('compose-to').value, cc: el('compose-cc').value, bcc: el('compose-bcc').value, subject: el('compose-subject').value, text: el('compose-text').value };\n"
      "    if (replyTo) { body.in_reply_to = replyTo.message_id; body.references = replyTo.references; body.answered_id = replyTo.id; }\n"
      "    return body;\n"
      "  };\n"
      "  el('compose-save').addEventListener('click', function () {\n"
      "    var body = composeBody();\n"
      "    if (draftId) { body.replace_id = draftId; }\n"
      "    readFiles().then(function (files) {\n"
      "    files = carried.concat(files);\n"
      "    if (files.length) { body.attachments = files; }\n"
      "    return call('POST', '/api/v1/me/drafts', body); }, function (why) { say('compose-status', why, false); return null; }).then(function (result) {\n"
      "      if (!result) { return; }\n"
      "      if (result.status === 201 && result.data) { draftId = result.data.id; say('compose-status', 'Draft saved.', true); loadFolders(); return; }\n"
      "      say('compose-status', describe(result, 'Could not save the draft'), false);\n"
      "    });\n"
      "  });\n"
      "  el('message-edit').addEventListener('click', function () {\n"
      "    if (!current) { return; }\n"
      "    draftId = current.id;\n"
      "    replyTo = null;\n"
      "    prefill(current.to || '', current.subject || '', current.text || '');\n"
      "    el('compose-cc').value = current.cc || '';\n"
      "    carryAttachments(current);\n"
      "  });\n"
      "  // The list as a list: a cursor the arrow keys move, Enter to open,\n"
      "  // a box per row, and one bar that acts on every box ticked - through\n"
      "  // the same one-message calls, one after another.\n"
      "  var listRows = [];\n"
      "  var cursor = -1;\n"
      "  var selected = {};\n"
      "  var setCursor = function (index) {\n"
      "    if (!listRows.length) { cursor = -1; return; }\n"
      "    cursor = Math.max(0, Math.min(listRows.length - 1, index));\n"
      "    listRows.forEach(function (r, i) { r.row.classList.toggle('msg-cursor', i === cursor); });\n"
      "    listRows[cursor].row.scrollIntoView({ block: 'nearest' });\n"
      "  };\n"
      "  var selectedIds = function () { return Object.keys(selected).filter(function (k) { return selected[k]; }).map(Number); };\n"
      "  var renderBulk = function () {\n"
      "    var ids = selectedIds();\n"
      "    el('bulk-bar').hidden = ids.length === 0;\n"
      "    el('bulk-count').textContent = ids.length + ' selected';\n"
      "    var select = el('bulk-move');\n"
      "    while (select.firstChild) { select.removeChild(select.firstChild); }\n"
      "    var homeId = Number(el('folder').value);\n"
      "    var home = allFolders.filter(function (f) { return f.id === homeId; })[0];\n"
      "    allFolders.forEach(function (f) {\n"
      "      if (f.id === homeId || !f.writable || (home && f.account_id !== home.account_id)) { return; }\n"
      "      var option = node('option', f.path); option.value = f.id; select.appendChild(option);\n"
      "    });\n"
      "  };\n"
      "  var clearSelection = function () { selected = {}; renderBulk(); };\n"
      "  // One call per message, in order, then one reload.\n"
      "  var eachSelected = function (act) {\n"
      "    var ids = selectedIds();\n"
      "    var chain = Promise.resolve();\n"
      "    ids.forEach(function (id) { chain = chain.then(function () { return act(id); }); });\n"
      "    return chain.then(function () { clearSelection(); loadFolders(); });\n"
      "  };\n"
      "  el('bulk-read').addEventListener('click', function () { eachSelected(function (id) { return call('PUT', '/api/v1/me/messages/' + id + '/flags', { seen: true }); }); });\n"
      "  el('bulk-unread').addEventListener('click', function () { eachSelected(function (id) { return call('PUT', '/api/v1/me/messages/' + id + '/flags', { seen: false }); }); });\n"
      "  el('bulk-delete').addEventListener('click', function () { eachSelected(function (id) { return call('DELETE', '/api/v1/me/messages/' + id); }); });\n"
      "  el('bulk-move-go').addEventListener('click', function () {\n"
      "    var target = Number(el('bulk-move').value);\n"
      "    if (!target) { return; }\n"
      "    eachSelected(function (id) { return call('POST', '/api/v1/me/messages/' + id + '/move', { folder_id: target }); });\n"
      "  });\n"
      "  el('bulk-clear').addEventListener('click', function () { clearSelection(); listRows.forEach(function (r) { r.box.checked = false; }); });\n"
      "  document.addEventListener('keydown', function (event) {\n"
      "    var tag = (event.target && event.target.tagName) || '';\n"
      "    if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || event.ctrlKey || event.metaKey || event.altKey) { return; }\n"
      "    if (el('account').hidden || !el('message-list').hidden === false) { return; }\n"
      "    if (event.key === 'ArrowDown' || event.key === 'j') { setCursor(cursor + 1); event.preventDefault(); }\n"
      "    else if (event.key === 'ArrowUp' || event.key === 'k') { setCursor(cursor - 1); event.preventDefault(); }\n"
      "    else if (event.key === 'Enter' && cursor >= 0) { openMessage(listRows[cursor].id); event.preventDefault(); }\n"
      "    else if (event.key === 'x' && cursor >= 0) { var r = listRows[cursor]; r.box.checked = !r.box.checked; selected[r.id] = r.box.checked; renderBulk(); event.preventDefault(); }\n"
      "  });\n"
      "  // Files: read in the browser and sent as base64 in the same call,\n"
      "  // twelve megabytes together at most.\n"
      "  var readFiles = function () {\n"
      "    var files = Array.prototype.slice.call(el('compose-files').files || []);\n"
      "    var total = files.reduce(function (n, f) { return n + f.size; }, 0);\n"
      "    if (files.length > 20) { return Promise.reject('At most 20 files.'); }\n"
      "    if (total > 12 * 1024 * 1024) { return Promise.reject('The files are larger than 12 MB together.'); }\n"
      "    return Promise.all(files.map(function (file) {\n"
      "      return new Promise(function (resolve, reject) {\n"
      "        var reader = new FileReader();\n"
      "        reader.onload = function () { resolve({ name: file.name, type: file.type || 'application/octet-stream', data: String(reader.result).split(',')[1] || '' }); };\n"
      "        reader.onerror = function () { reject('Could not read ' + file.name); };\n"
      "        reader.readAsDataURL(file);\n"
      "      });\n"
      "    }));\n"
      "  };\n"
      "  el('compose-files').addEventListener('change', function () {\n"
      "    var files = Array.prototype.slice.call(el('compose-files').files || []);\n"
      "    el('compose-files-note').textContent = files.length ? files.map(function (f) { return f.name + ' (' + format(f.size) + ')'; }).join(', ') : '';\n"
      "  });\n"
      "  // A session from an earlier visit is still good until it has been idle\n"
      "  // too long: try it first, and only ask for the password when it is not.\n"
      "  load(true);\n"
      "})();\n";

   // The page and its script share these. No inline script or style
   // source is allowed except the page's own stylesheet element;
   // connections go to this origin only; nothing may frame the page.
   const char *PortalHeaders =
      "Content-Security-Policy: default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; img-src data:; connect-src 'self'; frame-src 'self'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'\r\n"
      "X-Content-Type-Options: nosniff\r\n"
      "Referrer-Policy: no-referrer\r\n"
      "Cache-Control: no-store\r\n";
}
