// https://www.progressiverobot.com
// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using NUnit.Framework;
using NUnit.Framework.Legacy;   // StringAssert moved here in NUnit 4
using RegressionTests.Shared;

namespace RegressionTests.Infrastructure
{
   /// <summary>
   ///    The RFC 5424 syslog sink: the shape of the message on the wire, the
   ///    facility and severity arithmetic, the structured data, the UDP truncation
   ///    rule, and - the one that matters most - that a collector which is not
   ///    there neither delays a message nor loses one.
   ///
   ///    A UDP listener of its own, on a port nothing else in the suite uses, the
   ///    way the DNS and metrics fixtures stand their own servers up. It has to be
   ///    a real socket: the assertions here are about bytes, and every defect this
   ///    fixture exists to catch - a NILVALUE where a field should be, a facility
   ///    multiplied by the wrong number, a truncation that splits a character - is
   ///    invisible to anything that inspects the code rather than the datagram.
   ///
   ///    THE SETTINGS ARE WRITTEN BY LATE BINDING, on purpose. They are new
   ///    properties on IInterfaceLogging, and the checked-in
   ///    Interop.hMailServer.dll is regenerated by hand after an IDL change (see
   ///    Tools/Interop/README.md). Writing them early-bound would mean this file
   ///    does not compile until that regeneration has happened - which would stop
   ///    the whole suite building rather than failing one fixture. IDispatch is
   ///    registered whatever the interop says, so this works either way.
   /// </summary>
   [TestFixture]
   public class SyslogExport : TestFixtureBase
   {
      // Nothing else in the suite binds this. 9099 is the metrics listener and
      // 9096 is the OTLP collector; 514 is the real syslog port and must not be
      // taken on a machine that may be running one.
      private const int CollectorPort = 20514;

      // RFC 5424 severities.
      private const int SeverityWarning = 4;
      private const int SeverityInformational = 6;

      // RFC 5424 facilities.
      private const int FacilityMail = 2;
      private const int FacilityLocal0 = 16;

      // The Logger's own category bits, which the SyslogLogTypes mask is made of.
      private const int TransportUdp = 0;
      private const int TransportTcp = 1;

      private SyslogCollector collector_;

      /// <summary>
      ///    A UDP socket that keeps every datagram it is sent, as bytes. Bytes and
      ///    not strings: the message carries a UTF-8 byte-order mark and is
      ///    truncated by byte count, and both of those are assertions about bytes.
      /// </summary>
      private sealed class SyslogCollector : IDisposable
      {
         private readonly UdpClient udp_;
         private readonly Thread thread_;
         private readonly object lock_ = new object();
         private readonly List<byte[]> datagrams_ = new List<byte[]>();
         private volatile bool running_;

         public SyslogCollector(int port)
         {
            udp_ = new UdpClient(new IPEndPoint(IPAddress.Loopback, port));
            running_ = true;
            thread_ = new Thread(Run) { IsBackground = true };
            thread_.Start();
         }

         public List<byte[]> Snapshot()
         {
            lock (lock_)
               return new List<byte[]>(datagrams_);
         }

         public void Clear()
         {
            lock (lock_)
               datagrams_.Clear();
         }

         private void Run()
         {
            var any = new IPEndPoint(IPAddress.Any, 0);

            while (running_)
            {
               try
               {
                  byte[] datagram = udp_.Receive(ref any);
                  lock (lock_)
                     datagrams_.Add(datagram);
               }
               catch (Exception fatalCheck) when (!ExceptionPolicy.IsFatal(fatalCheck))
               {
                  return; // the socket was closed
               }
            }
         }

         public void Dispose()
         {
            running_ = false;
            try { udp_.Close(); }
            catch (Exception fatalCheck) when (!ExceptionPolicy.IsFatal(fatalCheck)) { /* Deliberately ignored: best effort only, and the outcome of the surrounding operation does not depend on this succeeding. */ }
            try { thread_.Join(2000); }
            catch (Exception fatalCheck) when (!ExceptionPolicy.IsFatal(fatalCheck)) { /* Deliberately ignored: best effort only, and the outcome of the surrounding operation does not depend on this succeeding. */ }
         }
      }

      // ---- the settings, late bound (see the fixture comment) -----------------

      private object Logging => _application.Settings.Logging;

      private void Set(string property, object value)
      {
         object logging = Logging;
         logging.GetType().InvokeMember(property, BindingFlags.SetProperty, null, logging, new[] { value });
      }

      private object Get(string property)
      {
         object logging = Logging;
         return logging.GetType().InvokeMember(property, BindingFlags.GetProperty, null, logging, null);
      }

      /// <summary>
      ///    Points the sink at the collector and restarts the listeners, which is
      ///    when SyslogSink::Start reads these settings.
      /// </summary>
      private void ConfigureSyslog(int transport, int facility, int minimumSeverity, int port = CollectorPort)
      {
         Set("SyslogHost", "127.0.0.1");
         Set("SyslogPort", port);
         Set("SyslogTransport", transport);
         Set("SyslogFacility", facility);
         Set("SyslogMinimumSeverity", minimumSeverity);
         Set("SyslogLogSMTP", true);
         Set("SyslogLogIMAP", true);
         Set("SyslogLogPOP3", true);
         Set("SyslogLogApplication", true);
         Set("SyslogLogTCPIP", false);
         Set("SyslogLogDebug", false);
         Set("SyslogEnabled", true);

         // Read back what was just written. An editor that can write a value and
         // not read it back misreports its own state on every load, which this
         // project treats as worse than having no editor - so the COM surface the
         // Control Panel uses is held to it here, once, rather than in a test of
         // its own.
         Assert.AreEqual(facility, Convert.ToInt32(Get("SyslogFacility")), "SyslogFacility did not read back.");
         Assert.AreEqual(minimumSeverity, Convert.ToInt32(Get("SyslogMinimumSeverity")), "SyslogMinimumSeverity did not read back.");
         Assert.AreEqual(transport, Convert.ToInt32(Get("SyslogTransport")), "SyslogTransport did not read back.");
         Assert.AreEqual(port, Convert.ToInt32(Get("SyslogPort")), "SyslogPort did not read back.");
         Assert.AreEqual("127.0.0.1", Convert.ToString(Get("SyslogHost")), "SyslogHost did not read back.");
         Assert.IsTrue(Convert.ToBoolean(Get("SyslogEnabled")), "SyslogEnabled did not read back.");
         Assert.IsFalse(Convert.ToBoolean(Get("SyslogLogDebug")), "SyslogLogDebug did not read back.");
         Assert.IsTrue(Convert.ToBoolean(Get("SyslogLogIMAP")), "SyslogLogIMAP did not read back.");

         _application.Reinitialize();
      }

      // Named rather than overriding: NUnit runs every [SetUp] in the hierarchy,
      // base first and derived last, and every [TearDown] the other way round. A
      // method that hid the base one by name would run instead of it.
      [SetUp]
      public void StartCollector()
      {
         collector_ = new SyslogCollector(CollectorPort);
      }

      [TearDown]
      public void StopCollectorAndDisableSyslog()
      {
         // Off first, then the restart, then the listener: leaving the sink
         // enabled would have every later fixture in the run sending datagrams
         // at a port nobody is listening on, and leaving the socket open would
         // fail this fixture's own next test at the bind.
         try
         {
            Set("SyslogEnabled", false);
            Set("SyslogHost", "");
            _application.Reinitialize();
         }
         catch (Exception fatalCheck) when (!ExceptionPolicy.IsFatal(fatalCheck))
         {
            // A test that killed the server cannot put the setting back. The base
            // teardown reports that failure; this must not replace it.
         }

         if (collector_ != null)
         {
            collector_.Dispose();
            collector_ = null;
         }
      }

      // ---- helpers ------------------------------------------------------------

      /// <summary>
      ///    Waits for a datagram whose text satisfies the predicate, and returns
      ///    every datagram received. Polls rather than sleeps once: the sink
      ///    batches on its own thread and a fixed wait is either flaky or slow.
      /// </summary>
      private List<byte[]> WaitFor(Func<string, bool> matches, int seconds = 30)
      {
         for (int attempt = 0; attempt < seconds * 4; attempt++)
         {
            List<byte[]> datagrams = collector_.Snapshot();
            if (datagrams.Any(datagram => matches(Text(datagram))))
               return datagrams;

            Thread.Sleep(250);
         }

         return collector_.Snapshot();
      }

      private static string Text(byte[] datagram) => Encoding.UTF8.GetString(datagram);

      private static string Describe(List<byte[]> datagrams)
      {
         if (datagrams.Count == 0)
            return "(no datagrams were received at all)";

         string joined = string.Join(Environment.NewLine, datagrams.Select(Text).Take(20));
         return joined.Length <= 4000 ? joined : joined.Substring(0, 4000) + "...";
      }

      // <PRI>1 TIMESTAMP HOSTNAME APP-NAME PROCID MSGID
      private static readonly Regex Header = new Regex(
         @"^<(?<pri>\d{1,3})>1 " +
         @"(?<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}(?:Z|[+-]\d{2}:\d{2})) " +
         @"(?<hostname>\S+) (?<app>\S+) (?<procid>\S+) (?<msgid>\S+) ",
         RegexOptions.Compiled);

      private static Match ParseHeader(string message)
      {
         Match match = Header.Match(message);
         Assert.IsTrue(match.Success, "Not an RFC 5424 message: " + message);
         return match;
      }

      private void GenerateMailActivity(string address)
      {
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, address, "test");
         SmtpClientSimulator.StaticSend("sender@external.example", address, "Syslog", "Body");
         string message = Pop3ClientSimulator.AssertGetFirstMessageText(address, "test");
         Assert.IsTrue(message.Contains("Body"), "The message was not delivered. Got: " + message);
      }

      // ---- the tests ----------------------------------------------------------

      [Test]
      [Description("Every field of the RFC 5424 header, the structured data and the UTF-8 byte-order mark, " +
                   "on a real datagram produced by real SMTP traffic.")]
      public void TestTheMessageOnTheWireIsRfc5424()
      {
         ConfigureSyslog(TransportUdp, FacilityMail, SeverityInformational);

         GenerateMailActivity("syslog-shape@example.test");

         List<byte[]> datagrams = WaitFor(text => text.Contains("SMTPD"));
         byte[] smtp = datagrams.FirstOrDefault(datagram => Text(datagram).Contains("SMTPD"));

         Assert.IsNotNull(smtp, "No SMTPD entry reached the collector. Received: " + Describe(datagrams));

         string message = Text(smtp);
         Match header = ParseHeader(message);

         // mail (2) * 8 + informational (6). An SMTP conversation line is not an
         // error and not debug, so this is the number every one of them carries.
         Assert.AreEqual(FacilityMail * 8 + SeverityInformational,
            int.Parse(header.Groups["pri"].Value, CultureInfo.InvariantCulture),
            "The priority is not facility * 8 + severity. Message: " + message);

         Assert.AreEqual("hMailServer", header.Groups["app"].Value,
            "APP-NAME should name this server. Message: " + message);

         Assert.AreNotEqual("-", header.Groups["hostname"].Value,
            "HOSTNAME should be the server's own name, not the NILVALUE. Message: " + message);

         Assert.IsTrue(int.TryParse(header.Groups["procid"].Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out int procid) && procid > 0,
            "PROCID should be the process id. Message: " + message);

         Assert.AreEqual("SMTPD", header.Groups["msgid"].Value,
            "MSGID should be the log category. Message: " + message);

         // A timestamp that parses, and that is this run's - not 1970, and not a
         // local time printed as though it were UTC.
         DateTimeOffset stamp = DateTimeOffset.Parse(header.Groups["timestamp"].Value,
            CultureInfo.InvariantCulture, DateTimeStyles.None);
         Assert.Less(Math.Abs((DateTimeOffset.Now - stamp).TotalMinutes), 10,
            "The timestamp is not close to now: " + header.Groups["timestamp"].Value);

         // Structured data: the private SD-ID, the thread, the session the line
         // belongs to and the peer it was talking to. A protocol line has all
         // three, which is the whole reason for having structured data at all.
         StringAssert.Contains("[hmailserver@32473 ", message);
         StringAssert.Contains("thread=\"", message);
         StringAssert.Contains("session=\"", message);
         StringAssert.Contains("client=\"", message);
         StringAssert.Contains("]", message);

         // The MSG is UTF-8 and says so, per RFC 5424 section 6.4. Asserted on the
         // bytes: the mark is three bytes and is invisible in a string comparison.
         int bom = IndexOfBom(smtp);
         Assert.Greater(bom, 0, "The MSG should be introduced by a UTF-8 byte-order mark. Message: " + message);
         Assert.Greater(smtp.Length, bom + 3, "There is a byte-order mark and no message after it: " + message);

         // And the structured data ends before the mark, rather than the mark
         // sitting inside a parameter.
         Assert.Less(message.IndexOf("[hmailserver@32473 ", StringComparison.Ordinal), bom,
            "The structured data must come before the MSG. Message: " + message);
      }

      [Test]
      [Description("The priority is facility * 8 + severity for a facility other than the default, " +
                   "and the minimum-severity setting suppresses everything less severe.")]
      public void TestFacilityAndSeverityArithmetic()
      {
         // local0, and errors and warnings only. Ordinary SMTP, POP3 and
         // application lines are informational (6), which is less severe than 4,
         // so none of them may be sent.
         ConfigureSyslog(TransportUdp, FacilityLocal0, SeverityWarning);

         GenerateMailActivity("syslog-severity@example.test");

         // A negative control needs a positive one, or "nothing arrived" is
         // indistinguishable from a sink that is not running at all. So: give the
         // filter time to have sent something, then assert on what is there.
         Thread.Sleep(3000);

         List<byte[]> datagrams = collector_.Snapshot();

         foreach (byte[] datagram in datagrams)
         {
            string message = Text(datagram);
            Match header = ParseHeader(message);

            int priority = int.Parse(header.Groups["pri"].Value, CultureInfo.InvariantCulture);
            Assert.AreEqual(FacilityLocal0, priority / 8,
               "Every entry should carry the configured facility. Message: " + message);

            Assert.LessOrEqual(priority % 8, SeverityWarning,
               "An entry less severe than the configured minimum was sent. Message: " + message);
         }

         Assert.IsFalse(datagrams.Any(datagram => Text(datagram).Contains(" SMTPD ")),
            "SMTP conversation lines are informational and must not pass a minimum of warning. Received: " +
            Describe(datagrams));

         // The same server, the same traffic, with the minimum put back: this is
         // the control that proves the filter above suppressed something rather
         // than nothing being produced.
         collector_.Clear();
         ConfigureSyslog(TransportUdp, FacilityLocal0, SeverityInformational);
         GenerateMailActivity("syslog-severity-control@example.test");

         List<byte[]> afterwards = WaitFor(text => text.Contains("SMTPD"));
         byte[] smtp = afterwards.FirstOrDefault(datagram => Text(datagram).Contains("SMTPD"));
         Assert.IsNotNull(smtp,
            "With the minimum at informational the same traffic must reach the collector. Received: " +
            Describe(afterwards));

         Assert.AreEqual(FacilityLocal0 * 8 + SeverityInformational,
            int.Parse(ParseHeader(Text(smtp)).Groups["pri"].Value, CultureInfo.InvariantCulture),
            "local0 is 16, so an informational entry is 16 * 8 + 6 = 134. Message: " + Text(smtp));
      }

      [Test]
      [Description("A log line longer than a UDP datagram may be is cut to 1024 bytes, header first, " +
                   "on a character boundary - and nothing larger is ever sent.")]
      public void TestUdpDatagramsAreTruncatedAt1024Bytes()
      {
         ConfigureSyslog(TransportUdp, FacilityMail, SeverityInformational);

         // A command line far longer than a datagram may be. The server logs what
         // it received whether it likes the command or not, which is exactly the
         // case that has to be truncated.
         string longArgument = new string('a', 1500);

         using (var connection = new TcpConnection())
         {
            Assert.IsTrue(connection.Connect(TestPorts.Actual(25)), "Could not connect to the SMTP listener.");
            connection.ReadUntil("220");
            connection.Send("HELO " + longArgument + "\r\n");
            connection.ReadUntil(new List<string> { "250", "500", "501", "554" });
            connection.Send("QUIT\r\n");
         }

         List<byte[]> datagrams = WaitFor(text => text.Contains("aaaaaaaaaa"));

         Assert.IsTrue(datagrams.Count > 0, "Nothing reached the collector at all.");

         foreach (byte[] datagram in datagrams)
         {
            Assert.LessOrEqual(datagram.Length, 1024,
               "A UDP datagram exceeded the 1024-byte limit (" + datagram.Length + " bytes): " + Text(datagram));
         }

         byte[] longest = datagrams.OrderByDescending(datagram => datagram.Length).First();

         Assert.Greater(longest.Length, 900,
            "The over-long line should have filled the datagram rather than being dropped. Received: " +
            Describe(datagrams));

         // The header survived the cut: a message with half a header cannot be
         // filed by anything, which is the failure this rule exists to avoid.
         ParseHeader(Text(longest));
         StringAssert.Contains("[hmailserver@32473 ", Text(longest));

         // And the cut fell on a character boundary: decoding the bytes strictly
         // throws if the last character was split.
         Assert.DoesNotThrow(
            () => new UTF8Encoding(false, true).GetString(longest),
            "The truncation split a UTF-8 character.");
      }

      [Test]
      [Description("A collector that refuses every connection neither delays a message nor loses one, " +
                   "and the server says so in the application log.")]
      public void TestARefusingCollectorNeitherBlocksNorLosesMail()
      {
         // A TCP collector on a port nothing is listening on. TCP rather than UDP
         // deliberately: UDP never learns that nobody is there, and the failure
         // this test exists for - a sink that blocks the logging thread on a
         // connect - can only happen on a connected transport.
         collector_.Dispose();
         collector_ = null;

         ConfigureSyslog(TransportTcp, FacilityMail, SeverityInformational, CollectorPort);

         string address = "syslog-dead-collector@example.test";
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, address, "test");

         // Every one of these writes several log lines, each of which reaches a
         // sink whose collector is refusing connections. If anything in the sink
         // blocked the logging thread, this is where it would show.
         var started = DateTime.UtcNow;

         for (int i = 0; i < 5; i++)
            SmtpClientSimulator.StaticSend("sender@external.example", address, "Dead collector " + i, "Body " + i);

         var elapsed = DateTime.UtcNow - started;

         Assert.Less(elapsed.TotalSeconds, 60,
            "Five deliveries took " + elapsed.TotalSeconds + " seconds with a syslog collector that refuses " +
            "connections. A log sink must never put a socket on the path a message takes.");

         // And every message is there. This is the assertion that matters: the
         // sink may drop log entries when the collector is gone, and may never
         // drop mail.
         Pop3ClientSimulator.AssertMessageCount(address, "test", 5);

         string log = LogHandler.ReadCurrentDefaultLog();
         StringAssert.Contains("Syslog:", log,
            "The server should say once in the application log that the collector is not accepting entries.");
      }

      [Test]
      [Description("A category that is switched off is not sent, and one that is switched on is - " +
                   "which is what the log-types setting has to mean.")]
      public void TestOnlyTheSelectedCategoriesAreSent()
      {
         ConfigureSyslog(TransportUdp, FacilityMail, SeverityInformational);

         Set("SyslogLogSMTP", false);
         _application.Reinitialize();

         collector_.Clear();

         GenerateMailActivity("syslog-categories@example.test");

         // POP3 is still on, so its lines are the proof that the sink is running
         // and that the absence of SMTPD below is a decision rather than silence.
         List<byte[]> datagrams = WaitFor(text => text.Contains("POP3D"));

         Assert.IsTrue(datagrams.Any(datagram => Text(datagram).Contains("POP3D")),
            "POP3 conversations are switched on and must be sent. Received: " + Describe(datagrams));

         Assert.IsFalse(datagrams.Any(datagram => Text(datagram).Contains(" SMTPD ")),
            "SMTP conversations are switched off and must not be sent. Received: " + Describe(datagrams));
      }

      /// <summary>The offset of the UTF-8 byte-order mark, or -1.</summary>
      private static int IndexOfBom(byte[] datagram)
      {
         for (int i = 0; i + 2 < datagram.Length; i++)
         {
            if (datagram[i] == 0xEF && datagram[i + 1] == 0xBB && datagram[i + 2] == 0xBF)
               return i;
         }

         return -1;
      }
   }
}
