// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using hMailServer;
using NUnit.Framework;
using RegressionTests.Infrastructure;
using RegressionTests.Shared;

namespace RegressionTests.SMTP
{
   /// <summary>
   /// Mail posted through a distribution list carried no RFC 2369 / RFC 2919 List-*
   /// headers at all. The header names existed in this codebase only in the DKIM
   /// oversigning list, which means they were signed if a sender happened to supply
   /// them and were never generated by the server. Gmail's and Yahoo's bulk sender
   /// rules expect list mail to identify itself and to offer an unsubscribe, so list
   /// traffic from this server was being scored as unidentified bulk mail.
   ///
   /// These tests pin three separate things, and the second two matter as much as the
   /// first:
   ///
   /// 1. The headers are actually present, with the values the RFCs specify, and
   ///    List-Post says NO for an announcement-only list rather than pointing
   ///    subscribers at an address the server will refuse them from.
   ///
   /// 2. The unsubscribe is mailto: only. An earlier attempt at this feature is the
   ///    reason for the explicit negative control: RFC 8058 one-click needs an HTTPS
   ///    endpoint that processes a POST, this server has none, and a receiver which
   ///    tries a one-click unsubscribe against a non-existent endpoint concludes the
   ///    unsubscribe is broken - which is worse for deliverability than offering no
   ///    unsubscribe at all. If someone later adds List-Unsubscribe-Post or an https
   ///    URL without also building the endpoint, this fails.
   ///
   /// 3. Ordinary mail is untouched, and a message that already belongs to a list
   ///    keeps the one List-Id it arrived with. The header-adding path loads the
   ///    message and rewrites it on disk, so anything which makes it run on messages
   ///    it should not is a data-integrity risk, not a cosmetic one.
   /// </summary>
   [TestFixture]
   public class DistributionListHeaders : TestFixtureBase
   {
      private const string Password = "test";

      // The test domain is created fresh by PerformBasicSetup with no catch-all
      // account, so the server falls back to postmaster at the list's own domain for
      // the owner-facing headers. RFC 5321 section 4.5.1 requires every domain to
      // accept mail there, which is why it is the fallback rather than a guess.
      private const string ExpectedOwner = "postmaster@example.test";

      private static int CountOccurrences(string haystack, string needle)
      {
         var count = 0;
         var index = haystack.IndexOf(needle, StringComparison.Ordinal);

         while (index >= 0)
         {
            count++;
            index = haystack.IndexOf(needle, index + needle.Length, StringComparison.Ordinal);
         }

         return count;
      }

      private DistributionList CreateListWithMember(string listAddress, string memberAddress)
      {
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, memberAddress, Password);

         var recipients = new List<string> { memberAddress };

         return SingletonProvider<TestSetup>.Instance.AddDistributionList(_domain, listAddress, recipients);
      }

      [Test]
      [Description("A posting to a public list carries the full RFC 2369 / RFC 2919 header set")]
      public void PublicListPostingCarriesListHeaders()
      {
         CreateListWithMember("list1@example.test", "member1@example.test");
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "poster@example.test", Password);

         SmtpClientSimulator.StaticSend("poster@example.test", "list1@example.test", "Mail 1", "Mail 1");

         var text = Pop3ClientSimulator.AssertGetFirstMessageText("member1@example.test", Password);

         // RFC 2919: the identifier has the syntax of a domain name, so the @ of the
         // list address becomes a dot.
         Assert.IsTrue(text.Contains("List-Id: <list1.example.test>" + Environment.NewLine), text);

         // RFC 2369: each value is a URL in angle brackets.
         Assert.IsTrue(text.Contains("List-Post: <mailto:list1@example.test>" + Environment.NewLine), text);
         Assert.IsTrue(text.Contains("List-Owner: <mailto:" + ExpectedOwner + ">" + Environment.NewLine), text);
         Assert.IsTrue(text.Contains("List-Help: <mailto:" + ExpectedOwner + "?subject=help>" + Environment.NewLine), text);
         Assert.IsTrue(
            text.Contains("List-Unsubscribe: <mailto:" + ExpectedOwner + "?subject=unsubscribe%20list1@example.test>" + Environment.NewLine),
            text);

         // The rewrite prepends header lines and copies the original message after
         // them. If it ever loses the body instead, every assertion above still
         // passes, so the body is checked explicitly.
         Assert.IsTrue(text.Contains("Subject: Mail 1"), text);
         Assert.IsTrue(text.Contains("Mail 1"), text);
         Assert.IsTrue(text.Contains("From: poster@example.test"), text);

         // Nothing about a distribution-list posting is an error condition, so the
         // new diagnostics must not have fired. Asserted here rather than left for
         // whichever fixture runs next.
         CustomAsserts.AssertNoReportedError();
      }

      [Test]
      [Description("The unsubscribe is mailto: only - no RFC 8058 one-click, because there is no endpoint to serve it")]
      public void UnsubscribeIsMailtoOnlyAndNotOneClick()
      {
         CreateListWithMember("list1@example.test", "member1@example.test");
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "poster@example.test", Password);

         SmtpClientSimulator.StaticSend("poster@example.test", "list1@example.test", "Mail 1", "Mail 1");

         var text = Pop3ClientSimulator.AssertGetFirstMessageText("member1@example.test", Password);

         Assert.IsTrue(text.Contains("List-Unsubscribe: <mailto:"), text);

         // RFC 8058 one-click. Advertising it without an HTTPS endpoint that accepts
         // the POST makes receivers treat the unsubscribe as broken.
         Assert.IsFalse(text.Contains("List-Unsubscribe-Post"), text);

         // And no https unsubscribe URL, for the same reason.
         Assert.IsFalse(text.Contains("List-Unsubscribe: <https"), text);
         Assert.IsFalse(text.Contains("List-Unsubscribe: <http"), text);

         CustomAsserts.AssertNoReportedError();
      }

      [Test]
      [Description("An announcement-only list says List-Post: NO rather than naming an address it will refuse")]
      public void AnnouncementListSaysListPostNo()
      {
         var list = CreateListWithMember("list1@example.test", "member1@example.test");
         var announcer = SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "announcer@example.test", Password);

         list.Mode = eDistributionListMode.eLMAnnouncement;
         list.RequireSenderAddress = announcer.Address;
         list.Save();

         SmtpClientSimulator.StaticSend(announcer.Address, "list1@example.test", "Mail 1", "Mail 1");

         var text = Pop3ClientSimulator.AssertGetFirstMessageText("member1@example.test", Password);

         // RFC 2369 defines NO as the value meaning postings are not accepted. The
         // server refuses anything not from RequireSenderAddress, so a subscriber
         // told to reply to the list would be told to reply into a 5xx.
         Assert.IsTrue(text.Contains("List-Post: NO" + Environment.NewLine), text);
         Assert.IsFalse(text.Contains("List-Post: <mailto:"), text);

         // The authorized poster is the only address hMailServer records for a list,
         // so it is used as the owner in preference to the postmaster fallback.
         Assert.IsTrue(text.Contains("List-Owner: <mailto:" + announcer.Address + ">" + Environment.NewLine), text);
         Assert.IsTrue(text.Contains("List-Id: <list1.example.test>" + Environment.NewLine), text);

         CustomAsserts.AssertNoReportedError();
      }

      [Test]
      [Description("Mail that did not go through a list gets no List-* headers at all")]
      public void OrdinaryMailGetsNoListHeaders()
      {
         var account = SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "test@example.test", Password);

         SmtpClientSimulator.StaticSend(account.Address, account.Address, "Mail 1", "Mail 1");

         var text = Pop3ClientSimulator.AssertGetFirstMessageText(account.Address, Password);

         // The negative control that matters most. The header-adding path rewrites
         // the message file, so it must not run for the overwhelming majority of
         // mail, which is not list mail.
         Assert.IsFalse(text.Contains("List-Id:"), text);
         Assert.IsFalse(text.Contains("List-Post:"), text);
         Assert.IsFalse(text.Contains("List-Help:"), text);
         Assert.IsFalse(text.Contains("List-Owner:"), text);
         Assert.IsFalse(text.Contains("List-Unsubscribe:"), text);

         CustomAsserts.AssertNoReportedError();
      }

      [Test]
      [Description("A list whose member is another list produces exactly one List-Id, naming the list that was posted to")]
      public void NestedListProducesASingleListId()
      {
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "member1@example.test", Password);

         var innerRecipients = new List<string> { "member1@example.test" };
         SingletonProvider<TestSetup>.Instance.AddDistributionList(_domain, "inner@example.test", innerRecipients);

         var outerRecipients = new List<string> { "inner@example.test" };
         SingletonProvider<TestSetup>.Instance.AddDistributionList(_domain, "outer@example.test", outerRecipients);

         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "poster@example.test", Password);

         SmtpClientSimulator.StaticSend("poster@example.test", "outer@example.test", "Mail 1", "Mail 1");

         var text = Pop3ClientSimulator.AssertGetFirstMessageText("member1@example.test", Password);

         // Expansion is recursive, so a naive implementation could add one set of
         // headers per level. RFC 2919 permits exactly one List-Id, and the list the
         // sender actually posted to is the one the message belongs to.
         // The needle keeps the trailing space on purpose: a DKIM-Signature h= tag
         // lists field names separated by colons ("...:List-Id:List-Help:..."), so
         // counting "List-Id:" alone would also count the signature if a key were
         // ever configured for the test domain.
         Assert.AreEqual(1, CountOccurrences(text, "List-Id: "), text);
         Assert.IsTrue(text.Contains("List-Id: <outer.example.test>" + Environment.NewLine), text);
         Assert.IsFalse(text.Contains("List-Id: <inner.example.test>"), text);

         CustomAsserts.AssertNoReportedError();
      }

      [Test]
      [Description("A message that already belongs to a list keeps the single List-Id it arrived with")]
      public void ExistingListIdIsNotDuplicated()
      {
         CreateListWithMember("list1@example.test", "member1@example.test");
         SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "poster@example.test", Password);

         // A message which has already travelled through some other mailing list and
         // is then posted to one of ours. Adding our own List-Id next to the existing
         // one would violate RFC 2919 and leave the receiver unable to tell which
         // list the subscriber actually joined.
         var raw = "From: poster@example.test\r\n" +
                   "To: list1@example.test\r\n" +
                   "Subject: Mail 1\r\n" +
                   "List-Id: <upstream.example.org>\r\n" +
                   "\r\n" +
                   "Mail 1\r\n";

         SmtpClientSimulator.StaticSendRaw("poster@example.test", "list1@example.test", raw);

         var text = Pop3ClientSimulator.AssertGetFirstMessageText("member1@example.test", Password);

         Assert.AreEqual(1, CountOccurrences(text, "List-Id: "), text);
         Assert.IsTrue(text.Contains("List-Id: <upstream.example.org>"), text);
         Assert.IsFalse(text.Contains("List-Id: <list1.example.test>"), text);

         CustomAsserts.AssertNoReportedError();
      }
   }
}
