// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd
// http://www.hmailserver.com

#pragma once

namespace HM
{
   class Account;
   class Message;
   class MessageData;

   // The decisions the legacy rules engine either got wrong or never made.
   //
   // Rules run on every message, twice - once as the global set in SMTPDeliverer
   // before the recipient split, and once per recipient as the account set in
   // LocalDelivery - so a wrong decision in here is not a wrong decision about one
   // message, it is a wrong decision about all mail. That is why these live in their
   // own unit with the reasoning written down rather than inline in RuleApplier: each
   // one exists because of a specific defect, and a defect whose only record is the
   // shape of the code is a defect that comes back.
   //
   // Nothing in here decides whether a rule matches. It decides when the engine is
   // entitled to an answer at all, what a generated message has to carry, and what to
   // do about a criterion that cannot answer cheaply or cannot answer at all.
   class RuleGuard
   {
   public:
      // May the rule set be applied to this message?
      //
      // THE DEFECT. RuleApplier::ApplyRules built a MessageData, called
      // LoadFromMessage on it, and threw the bool away. There are two ways that goes
      // wrong and both end with the engine holding an all-empty MessageData:
      //
      //   * LoadFromMessage returns false for a file over 80 MB and for a file whose
      //     MIME parse threw (the path that copies the file to "Problematic
      //     messages" and reports HM4218). The caller never looked.
      //
      //   * LoadFromMessage returns TRUE when it could not open the file at all.
      //     Its bNewMessage branch exists for a message being composed from nothing -
      //     it sets a default charset and MIME-Version and reports success - and it
      //     cannot tell that case apart from "this message exists on disk and I could
      //     not read it", because both arrive as MimeBody::LoadFromFile returning
      //     false. This is the reachable half: a file briefly locked by a scanner or a
      //     backup is enough.
      //
      // An empty MessageData is not a harmless one. Every criterion is then compared
      // against an empty string, and the comparison types that match on empty are
      // exactly the ones people write filters with: NotEquals, NotContains, and
      // LessThan against any positive number. So "Subject NotContains [approved] ->
      // Delete", a rule its author would call conservative, deletes the message. A
      // rule that moves rather than deletes files it somewhere the user does not look,
      // which is the same loss with a longer fuse.
      //
      // Returns false when the engine must not run. The caller then delivers the
      // message normally: unfiltered mail in an inbox is recoverable and deleted mail
      // is not, so this fails open on purpose. Reports HM6040, because a message this
      // server accepted and now cannot read is a fault an administrator has to see
      // rather than an operational condition - it cannot happen to a healthy message,
      // which is also why it cannot fire on a default configuration.
      static bool MessageIsUsableForRules(bool loadSucceeded,
                                          std::shared_ptr<const Account> account,
                                          std::shared_ptr<Message> message);

      // The X-hMailServer-LoopCount value a message generated by a rule must carry.
      //
      // THE DEFECT. ApplyAction_Reply creates a brand-new Message, loads a MessageData
      // over the (not yet existing) file for it, and calls IncreaseRuleLoopCount() on
      // THAT. GetRuleLoopCount() on a message with no X-hMailServer-LoopCount header
      // returns 0, so the reply always went out carrying 1, whatever the message that
      // triggered it carried. The count is not a property of the generated message, it
      // is the depth of the chain that produced it, and a generator that starts it
      // again at 1 hands every reply a fresh budget of RuleLoopLimit hops.
      //
      // Forward and CreateCopy are correct by construction rather than by care: they
      // start from PersistentMessage::CopyToQueue, so the header is already in the
      // copied file and Increase really does mean +1. Reply is the only rule action
      // that builds its message from nothing, and it is the only one that lost the
      // count. The two other generators in this tree that build from nothing both do
      // it right and are the reference: SMTPDeliverer::SubmitErrorLog_ does
      // SetRuleLoopCount(iRuleLoopCount + 1), and SieveVacationResponder does
      // SetRuleLoopCount(decision.loopCount + 1) - the Sieve path had this same defect
      // and was fixed by carrying the count forward.
      //
      // Why it matters even though Reply also sets Auto-Submitted: the Forward action
      // deliberately does NOT honour Auto-Submitted (see the comment on the
      // IsGeneratedResponseAllowed call in ApplyAction_Forward - a forward is not a
      // generated response), so a chain that alternates reply and forward is guarded
      // by the counter and by nothing else. Restarting the counter at every reply
      // makes that chain unbounded.
      static int LoopCountForGeneratedMessage(std::shared_ptr<MessageData> source);

      // Applies LoopCountForGeneratedMessage. Call this instead of
      // IncreaseRuleLoopCount() whenever the generated message is a NEW message rather
      // than a copy of the source: on a copy the two agree, on a new message Increase
      // silently means "1".
      static void CarryLoopCountForward(std::shared_ptr<MessageData> source,
                                        std::shared_ptr<MessageData> generated);

      // A regular-expression criterion, with the two answers it could not previously
      // give.
      //
      // WHAT WAS WRONG. RuleApplier called RegularExpression::TestExactMatch, which
      // wraps the whole thing in catch (std::runtime_error) and returns false. Boost
      // raises that for two completely different situations, and collapsing both into
      // "did not match" costs something different in each:
      //
      //   * The pattern will not compile. A typo in a criterion - one unmatched
      //     bracket - produces a rule that is Active in the editor, matches nothing,
      //     ever, and says nothing about it. That is the failure mode that is worst to
      //     diagnose, because the rule looks like it is working and the mail looks
      //     like it was not supposed to match.
      //
      //   * Boost gave up mid-match. Its state-count heuristic raises
      //     error_complexity, so a catastrophically backtracking pattern is bounded
      //     rather than infinite - but the bound scales with the size of the pattern,
      //     and the criterion column is nvarchar(255), so a pattern near that length
      //     buys a budget in the tens of millions of states. Bounded is not cheap, and
      //     nothing stopped the cost being re-incurred on the next message, and the
      //     one after that. A sender who has learnt that a domain's rule set contains
      //     an expensive pattern pays once per message to make the server pay per
      //     message, which is the amplification that turns a slow regex into a denial
      //     of service.
      //
      // So both are reported, and in both cases the pattern is suspended for a cooling
      // window: a pattern that has just proved it cannot answer, or cannot answer
      // cheaply, is not asked again on the next message. An evaluation that merely
      // takes longer than the budget is treated the same way, because a wall-clock
      // measurement catches the expensive-but-successful case that Boost never
      // complains about.
      //
      // Suspended means "this criterion does not match", which is the fail-open
      // direction: there is no NotMatchesRegEx match type, so a regex criterion can
      // only ever make a rule fire, and a rule that does not fire leaves the message
      // where it already is. Suspension is keyed on the pattern text, so correcting a
      // pattern takes effect on the next message rather than after the window.
      //
      // HM6042 (will not compile) and HM6043 (too expensive) are emitted at most once
      // per pattern per window, so neither a hostile stream nor a busy server can turn
      // this into a log flood of its own.
      static bool RegexCriteriaMatches(const String &pattern, const String &subject);

      // The same breaker for the Sieve ":regex" match type (draft-ietf-sieve-regex),
      // which differs from a rule criterion in exactly two ways: it is a SEARCH
      // (the pattern may hit anywhere in the value; a rule criterion must match the
      // whole value), and its case behaviour follows the script's comparator
      // (i;ascii-casemap folds case, i;octet does not) rather than being fixed.
      //
      // Deliberately a parallel sibling of RegexCriteriaMatches rather than a shared
      // core: the two share the suspension table, the budget and the error codes
      // (HM6042/HM6043), but each keeps its own exact log wording, and the rules
      // path stays character-for-character what it was. If you change one, look at
      // the other. Suspension is keyed on the pattern text alone, so a pattern
      // suspended by a rule is also suspended for scripts and vice versa - the
      // breaker's question is "is this pattern affordable", which does not depend
      // on who asked.
      static bool SieveRegexMatches(const String &pattern, const String &subject, bool caseSensitive);

      // A rule action failed and may have left the message file in a state nobody
      // chose.
      //
      // THE DEFECT. ApplyAction_SetHeader ends with pMsgData->Write(fileName) and
      // ignores the result. Write is not atomic - MimeBody::SaveAllToFile rewrites the
      // file in place - so a failure part-way through leaves a message that is neither
      // the original nor the rewritten one, and delivery then continues with it as if
      // nothing had happened. Nothing was logged, which is the reason this has never
      // been reported by anyone: a message that arrives with its body missing looks
      // like a sender problem.
      //
      // This does not repair anything; by the time we know, the bytes are gone. It
      // makes the failure visible at High severity, naming the file, so that the
      // correlation between "a rule sets a header" and "some messages arrive empty"
      // can be made at all.
      static void ReportActionFailed(const String &actionName, const String &detail);

      // The ceilings, exposed because they are part of the contract rather than
      // implementation details: anyone reasoning about why a rule stopped matching
      // needs the numbers.
      static unsigned int RegexBudgetMilliseconds();
      static unsigned int RegexSuspensionSeconds();
   };
}
