// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd

#pragma once

namespace HM
{
   class Message;
   class MessageData;
   class MimeBody;
   class DistributionList;

   // Adds the RFC 2369 / RFC 2919 List-* headers to a message which was posted to a
   // local distribution list. Gmail's and Yahoo's bulk sender rules expect list mail
   // to carry them; before this, the header names appeared in this codebase only in
   // the DKIM oversigning list, meaning they were signed if a sender happened to
   // supply them and never generated by the server.
   //
   // Deliberately does NOT emit List-Unsubscribe-Post or an https unsubscribe URL.
   // RFC 8058 one-click requires an HTTPS endpoint which processes a POST, and this
   // server has none; a one-click header pointing at nothing is worse than no header
   // at all, because receivers conclude the unsubscribe mechanism is broken.
   class DistributionListSender
   {
   public:

      // Call from SMTPConnection::DoPreAcceptMessageModifications_, after the
      // existing spam-header/signature Write. Does nothing at all - not even a file
      // open - for a message which was not posted to a distribution list, which is
      // the overwhelmingly common case.
      static void AddListHeaders(std::shared_ptr<Message> message);

   private:

      static std::shared_ptr<const DistributionList> FindPostedList_(std::shared_ptr<Message> message);
      static bool LoadedMessageIsGenuine_(std::shared_ptr<MessageData> message_data);
      static void AppendFieldIfAbsent_(String &header_lines, std::shared_ptr<MimeBody> mime, const char *field_name, const String &field_value);
      static String DetermineOwnerAddress_(std::shared_ptr<const DistributionList> list);
      static bool IsUsAscii_(const String &value);
      static bool PrependHeaderLines_(const String &message_file_name, const String &header_lines, std::shared_ptr<Message> message, long original_size);
   };
}
