// Copyright (c) 2026 Christopher Holloway / Progressive Robot Ltd
// https://www.progressiverobot.com

#include "StdAfx.h"
#include "QuotaWarner.h"

#include "RecipientParser.h"

#include "../Common/BO/Account.h"
#include "../Common/BO/Message.h"
#include "../Common/BO/MessageData.h"
#include "../Common/BO/MessageRecipients.h"
#include "../Common/Application/Configuration.h"
#include "../Common/Persistence/PersistentServerMessage.h"
#include "../Common/BO/ServerMessages.h"
#include "../Common/Application/IniFileSettings.h"
#include "../Common/Cache/AccountSizeCache.h"
#include "../Common/Persistence/PersistentMessage.h"
#include "../Common/Util/Time.h"

#ifdef _DEBUG
#define DEBUG_NEW new(_NORMAL_BLOCK, __FILE__, __LINE__)
#define new DEBUG_NEW
#endif

namespace HM
{
   void
   QuotaWarner::NotifyIfThresholdCrossed(std::shared_ptr<const Account> account, __int64 messageSize)
   {
      try
      {
         if (!account)
            return;

         const int percent = IniFileSettings::Instance()->GetQuotaWarningPercent();

         if (percent <= 0 || percent > 100)
            return;

         const int maxSizeMB = account->GetAccountMaxSize();

         if (maxSizeMB <= 0)
            return;

         const __int64 quotaBytes = ((__int64) maxSizeMB) * 1024 * 1024;
         const __int64 thresholdBytes = quotaBytes / 100 * percent;

         const __int64 before = AccountSizeCache::Instance()->GetSize(account->GetID());
         const __int64 after = before + messageSize;

         // The crossing, and only the crossing. Reading this as "is it over the
         // threshold" instead would warn on every delivery from here on.
         if (before >= thresholdBytes || after < thresholdBytes)
            return;

         String body = Configuration::Instance()->GetServerMessages()->GetMessage("QUOTA_WARNING");
         String subject = Configuration::Instance()->GetServerMessages()->GetMessage("QUOTA_WARNING_SUBJECT");

         const int usedMB = (int) (after / 1024 / 1024);
         const int usedPercent = (int) (after * 100 / quotaBytes);

         body.Replace(_T("%MACRO_MAILBOX%"), account->GetAddress());
         body.Replace(_T("%MACRO_QUOTA%"), StringParser::IntToString(maxSizeMB));
         body.Replace(_T("%MACRO_USED%"), StringParser::IntToString(usedMB));
         body.Replace(_T("%MACRO_PERCENT%"), StringParser::IntToString(usedPercent));

         std::shared_ptr<Message> message = std::shared_ptr<Message>(new Message());
         message->SetState(Message::Delivering);

         std::shared_ptr<const Account> noAccount;
         std::shared_ptr<MessageData> messageData = std::shared_ptr<MessageData>(new MessageData());
         messageData->LoadFromMessage(noAccount, message);

         messageData->GenerateMessageID();
         messageData->SetSentTime(Time::GetCurrentMimeDate());

         // From the postmaster of the recipient's own domain rather than a
         // mailer-daemon address: this is not a bounce, it is the server telling
         // somebody something about their own mailbox, and a reply to it should reach
         // whoever runs the server.
         messageData->SetFrom(GetSenderAddress_(account->GetAddress()));
         messageData->SetTo(account->GetAddress());
         messageData->SetSubject(subject);
         messageData->SetBody(body);

         // Auto-generated (RFC 3834), so an out-of-office reply does not answer it and
         // the rule loop counter stops a rule from generating another one.
         messageData->SetAutoGenerated();
         messageData->IncreaseRuleLoopCount();

         if (!messageData->WriteReported(PersistentMessage::GetFileName(message), "A mailbox quota warning"))
            return;

         bool recipientOK = false;
         RecipientParser recipientParser;
         recipientParser.CreateMessageRecipientList(account->GetAddress(), message->GetRecipients(), recipientOK);

         if (message->GetRecipients()->GetCount() == 0)
         {
            FileUtilities::DeleteFile(PersistentMessage::GetFileName(message));
            return;
         }

         if (!PersistentMessage::SaveObject(message))
         {
            FileUtilities::DeleteFile(PersistentMessage::GetFileName(message));

            ErrorManager::Instance()->ReportError(ErrorManager::Medium, 6160, "QuotaWarner::NotifyIfThresholdCrossed",
               "A mailbox quota warning could not be saved and has not been sent, so the account holder has not "
               "been told their mailbox is nearly full. Its file has been removed rather than left on disk with "
               "nothing referring to it.");

            return;
         }

         LOG_APPLICATION(Formatter::Format("Quota warning: {0} has passed {1}% of its {2} MB quota and has been notified.",
                                           account->GetAddress(), percent, maxSizeMB));

         Application::Instance()->SubmitPendingEmail();
      }
      catch (...)
      {
         // Swallowed, like the message trace and for the same reason: this runs on the
         // delivery path, and a warning that can interrupt a delivery is worse than no
         // warning. A notice nobody receives is a missed courtesy; an exception here
         // is undelivered mail.
         ErrorManager::Instance()->ReportError(ErrorManager::Medium, 6161, "QuotaWarner::NotifyIfThresholdCrossed",
            "An error occurred while sending a mailbox quota warning. The delivery it was triggered by is unaffected.");
      }
   }

   String
   QuotaWarner::GetSenderAddress_(const String &recipientAddress)
   {
      // postmaster@<the recipient's own domain>. Deliberately not a configured
      // address: the notice is about one mailbox on one domain, and the person who
      // can do something about it is that domain's postmaster.
      String domain = StringParser::ExtractDomain(recipientAddress);

      if (domain.IsEmpty())
         return String();

      return "postmaster@" + domain;
   }
}
